import { REGIONS, type Region } from '../../src/shared/regions'

type RegionMap = Record<string, Region>

const countryDefault: Record<string, Region> = {
  Albania: 'Alps',
  Andorra: 'Pyrenees',
  Argentina: 'Andes',
  Armenia: 'Carpathians',
  Australia: 'Appalachians',
  Austria: 'Alps',
  Azerbaijan: 'Carpathians',
  Belarus: 'Carpathians',
  Belgium: 'Alps',
  'Bosnia and Herzegovina': 'Carpathians',
  Brazil: 'Andes',
  Bulgaria: 'Carpathians',
  Canada: 'Rockies (Canadian)',
  Chile: 'Andes',
  China: 'Carpathians',
  Croatia: 'Carpathians',
  Cyprus: 'Alps',
  Czechia: 'Carpathians',
  Denmark: 'Scandinavia',
  Egypt: 'Alps',
  Estonia: 'Scandinavia',
  Finland: 'Scandinavia',
  France: 'Alps',
  Georgia: 'Carpathians',
  Germany: 'Alps',
  Greece: 'Carpathians',
  Greenland: 'Scandinavia',
  Hungary: 'Carpathians',
  Iceland: 'Iceland',
  India: 'Carpathians',
  Iran: 'Carpathians',
  Ireland: 'Appalachians',
  Israel: 'Alps',
  Italy: 'Alps',
  Japan: 'Japanese Alps',
  Kazakhstan: 'Carpathians',
  Kosovo: 'Carpathians',
  Kyrgyzstan: 'Carpathians',
  Latvia: 'Scandinavia',
  Lebanon: 'Alps',
  Lesotho: 'Andes',
  Liechtenstein: 'Alps',
  Lithuania: 'Scandinavia',
  Mexico: 'Rockies (US)',
  Mongolia: 'Carpathians',
  Montenegro: 'Carpathians',
  Morocco: 'Alps',
  Netherlands: 'Alps',
  'New Zealand': 'New Zealand',
  'North Korea': 'Japanese Alps',
  'North Macedonia': 'Carpathians',
  Norway: 'Scandinavia',
  Pakistan: 'Carpathians',
  Poland: 'Carpathians',
  Portugal: 'Pyrenees',
  Romania: 'Carpathians',
  Russia: 'Carpathians',
  Serbia: 'Carpathians',
  Slovakia: 'Carpathians',
  Slovenia: 'Alps',
  'South Africa': 'Andes',
  'South Korea': 'South Korea',
  Spain: 'Pyrenees',
  Sweden: 'Scandinavia',
  Switzerland: 'Alps',
  Taiwan: 'Japanese Alps',
  Tajikistan: 'Carpathians',
  Turkey: 'Alps',
  Ukraine: 'Carpathians',
  'United Kingdom': 'Scottish Highlands',
  'United States': 'Rockies (US)',
  Uzbekistan: 'Carpathians',
}

const regionOverrides: Record<string, RegionMap> = {
  Argentina: {
    'Buenos Aires': 'Andes',
    Chubut: 'Andes',
    Mendoza: 'Andes',
    Neuquen: 'Andes',
    'Rio Negro': 'Andes',
    'Santa Cruz': 'Andes',
    'Tierra del Fuego': 'Andes',
  },
  Australia: {
    'New South Wales': 'Appalachians',
    Tasmania: 'Appalachians',
    Victoria: 'Appalachians',
    'Australian Capital Territory': 'Appalachians',
  },
  Austria: {
    Tyrol: 'Alps',
    Salzburg: 'Alps',
    Vorarlberg: 'Alps',
    Carinthia: 'Alps',
    Styria: 'Alps',
    'Lower Austria': 'Alps',
    'Upper Austria': 'Alps',
    Burgenland: 'Alps',
  },
  Canada: {
    Alberta: 'Rockies (Canadian)',
    'British Columbia': 'Rockies (Canadian)',
    Quebec: 'Appalachians',
    Ontario: 'Appalachians',
    Manitoba: 'Appalachians',
    'New Brunswick': 'Appalachians',
    'Newfoundland and Labrador': 'Appalachians',
    'Northwest Territories': 'Rockies (Canadian)',
    'Nova Scotia': 'Appalachians',
    'Prince Edward Island': 'Appalachians',
    Saskatchewan: 'Appalachians',
    Yukon: 'Rockies (Canadian)',
  },
  China: {
    Beijing: 'Carpathians',
    Hebei: 'Carpathians',
    Heilongjiang: 'Carpathians',
    Jilin: 'Carpathians',
    Xinjiang: 'Carpathians',
    'Inner Mongolia': 'Carpathians',
    Shanxi: 'Carpathians',
    Shandong: 'Carpathians',
    Sichuan: 'Carpathians',
    Gansu: 'Carpathians',
    Yunnan: 'Carpathians',
    Guizhou: 'Carpathians',
    Hubei: 'Carpathians',
    Hunan: 'Carpathians',
    Anhui: 'Carpathians',
    Guangdong: 'Carpathians',
    Zhejiang: 'Carpathians',
    Jiangsu: 'Carpathians',
    Jiangxi: 'Carpathians',
    Chongqing: 'Carpathians',
    Liaoning: 'Carpathians',
    Shaanxi: 'Carpathians',
    Qinghai: 'Carpathians',
    Tianjin: 'Carpathians',
    'Ningxia Hui': 'Carpathians',
    Henan: 'Carpathians',
  },
  Czechia: {
    'Moravian-Silesian': 'Carpathians',
    'South Moravian': 'Carpathians',
    Hradec: 'Carpathians',
    Liberec: 'Carpathians',
    Olomouc: 'Carpathians',
    Zlin: 'Carpathians',
    'Central Bohemian': 'Carpathians',
    Karlovy: 'Alps',
    Pardubice: 'Carpathians',
    Plzen: 'Alps',
    'South Bohemian': 'Alps',
    Vysocina: 'Carpathians',
    Ustecky: 'Alps',
  },
  Finland: {
    Lapland: 'Scandinavia',
    'Northern Ostrobothnia': 'Scandinavia',
    Kainuu: 'Scandinavia',
  },
  France: {
    Savoie: 'Alps',
    'Haute-Savoie': 'Alps',
    Isere: 'Alps',
    'Alpes-Maritimes': 'Alps',
    'Hautes-Alpes': 'Alps',
    'Alpes-de-Haute-Provence': 'Alps',
    Bouches: 'Alps',
    Var: 'Alps',
    Drome: 'Alps',
    Ain: 'Alps',
    'Pyrénées-Atlantiques': 'Pyrenees',
    'Hautes-Pyrénées': 'Pyrenees',
    'Pyrénées-Orientales': 'Pyrenees',
    Ariege: 'Pyrenees',
    Haute: 'Pyrenees',
    Jura: 'Alps',
    Doubs: 'Alps',
    'Territoire de Belfort': 'Alps',
    'Bas-Rhin': 'Alps',
    'Haut-Rhin': 'Alps',
    Moselle: 'Alps',
    Vosges: 'Alps',
    Cantal: 'Alps',
    Puy: 'Alps',
    'Haute-Loire': 'Alps',
    Loire: 'Alps',
    Allier: 'Alps',
    Gard: 'Alps',
    Aude: 'Pyrenees',
    Aveyron: 'Pyrenees',
    Corse: 'Alps',
    Lozere: 'Alps',
    Ardeche: 'Alps',
    Vaucluse: 'Alps',
  },
  Germany: {
    Bavaria: 'Alps',
    'Baden-Württemberg': 'Alps',
    Saxony: 'Alps',
    'Saxony-Anhalt': 'Alps',
    Thuringia: 'Alps',
    'North Rhine-Westphalia': 'Alps',
    Hesse: 'Alps',
    'Lower Saxony': 'Alps',
    'Rhineland-Palatinate': 'Alps',
  },
  Greece: {
    'Central Macedonia': 'Carpathians',
    Epirus: 'Carpathians',
    Thessaly: 'Carpathians',
    'West Macedonia': 'Carpathians',
    'Central Greece': 'Carpathians',
    Peloponnese: 'Carpathians',
    'Western Greece': 'Carpathians',
  },
  Iceland: {
    Austurland: 'Iceland',
    'Capital Region': 'Iceland',
    Northeast: 'Iceland',
    Northwest: 'Iceland',
    South: 'Iceland',
    Westfjords: 'Iceland',
  },
  Italy: {
    'Bolzano/Bozen': 'Alps',
    Trento: 'Alps',
    "Valle D'Aosta": 'Alps',
    'Aosta Valley': 'Alps',
    Turin: 'Alps',
    Sondrio: 'Alps',
    Bergamo: 'Alps',
    Brescia: 'Alps',
    Belluno: 'Alps',
    Udine: 'Alps',
    Vicenza: 'Alps',
    Verona: 'Alps',
    Como: 'Alps',
    'Verbano-Cusio-Ossola': 'Alps',
    Varese: 'Alps',
    Lecco: 'Alps',
    Cuneo: 'Alps',
    Alessandria: 'Alps',
    Vercelli: 'Alps',
    Novara: 'Alps',
    Biella: 'Alps',
    Piacenza: 'Alps',
    Pavia: 'Alps',
    Genova: 'Alps',
    Savona: 'Alps',
    Imperia: 'Alps',
    Bologna: 'Alps',
    Pistoia: 'Alps',
    Modena: 'Alps',
    "Reggio Nell'Emilia": 'Alps',
    Parma: 'Alps',
    Gorizia: 'Alps',
    Pordenone: 'Alps',
    Treviso: 'Alps',
    Lucca: 'Alps',
    Massa: 'Alps',
    Pescara: 'Alps',
    "L'Aquila": 'Alps',
    Teramo: 'Alps',
    Ascoli: 'Alps',
    Rieti: 'Alps',
    Perugia: 'Alps',
    Macerata: 'Alps',
    Arezzo: 'Alps',
    Palermo: 'Alps',
    Catania: 'Alps',
    Cosenza: 'Alps',
    Crotone: 'Alps',
    Potenza: 'Carpathians',
  },
  Japan: {
    'Hokkaido Prefecture': 'Hokkaido',
  },
  Poland: {
    'Lesser Poland Voivodeship': 'Tatra Mountains',
    'Silesian Voivodeship': 'Tatra Mountains',
    dolnoslaskie: 'Carpathians',
    Podkarpackie: 'Tatra Mountains',
    Malopolskie: 'Tatra Mountains',
  },
  Romania: {
    Brasov: 'Carpathians',
    Prahova: 'Carpathians',
    Harghita: 'Carpathians',
    Covasna: 'Carpathians',
    Mures: 'Carpathians',
    Sibiu: 'Carpathians',
    Alba: 'Carpathians',
    Bihor: 'Carpathians',
    Caras: 'Carpathians',
    Hunedoara: 'Carpathians',
    Neamt: 'Carpathians',
    Suceava: 'Carpathians',
    Bistrita: 'Carpathians',
    Maramures: 'Carpathians',
    Bacau: 'Carpathians',
    Dambovita: 'Carpathians',
    Gorj: 'Carpathians',
    Valcea: 'Carpathians',
    Cluj: 'Carpathians',
    Timis: 'Carpathians',
    Iasi: 'Carpathians',
  },
  'South Korea': {
    'Kangwon-Do': 'South Korea',
    'Gyeongsangnam-Do': 'South Korea',
    'Jeollabuk-Do': 'South Korea',
    'Kyeongki-Do': 'South Korea',
  },
  Spain: {
    Catalonia: 'Pyrenees',
    Barcelona: 'Pyrenees',
    Girona: 'Pyrenees',
    Lleida: 'Pyrenees',
    Huesca: 'Pyrenees',
    Asturias: 'Pyrenees',
    Cantabria: 'Pyrenees',
    Leon: 'Pyrenees',
    'La Rioja': 'Pyrenees',
    Navarra: 'Pyrenees',
    Avila: 'Pyrenees',
    Segovia: 'Pyrenees',
    Soria: 'Pyrenees',
    Teruel: 'Pyrenees',
    Guadalajara: 'Pyrenees',
    Salamanca: 'Pyrenees',
    Granada: 'Pyrenees',
    Madrid: 'Pyrenees',
    Ourense: 'Pyrenees',
  },
  Sweden: {
    Jamtland: 'Scandinavia',
    Vasternorrland: 'Scandinavia',
    Dalarna: 'Scandinavia',
    'Vasterbotten County': 'Scandinavia',
    Norrbotten: 'Scandinavia',
    Gavleborg: 'Scandinavia',
    Varmland: 'Scandinavia',
    Ostergotland: 'Scandinavia',
    Sodermanland: 'Scandinavia',
    Stockholm: 'Scandinavia',
    Uppsala: 'Scandinavia',
    Blekinge: 'Scandinavia',
    Halland: 'Scandinavia',
    Kalmar: 'Scandinavia',
    Jonkoping: 'Scandinavia',
    'Vastra Gotaland': 'Scandinavia',
    Vastmanland: 'Scandinavia',
    Skane: 'Scandinavia',
  },
  Switzerland: {
    Valais: 'Alps',
    Graubunden: 'Alps',
    Bern: 'Alps',
    Vaud: 'Alps',
    Obwalden: 'Alps',
    Nidwalden: 'Alps',
    Uri: 'Alps',
    Schwyz: 'Alps',
    Glarus: 'Alps',
    'Saint Gallen': 'Alps',
    Ticino: 'Alps',
    Zurich: 'Alps',
    Lucerne: 'Alps',
    Aargau: 'Alps',
    Fribourg: 'Alps',
    Neuchatel: 'Alps',
    Jura: 'Alps',
    Thurgau: 'Alps',
    Zug: 'Alps',
    Appenzell: 'Alps',
    Solothurn: 'Alps',
    'Basel-Country': 'Alps',
  },
  Turkey: {
    Erzurum: 'Alps',
    Bursa: 'Alps',
    Kayseri: 'Alps',
    Kars: 'Alps',
    Erzincan: 'Alps',
    Bingol: 'Alps',
    Bitlis: 'Alps',
    Gumushane: 'Alps',
    Sivas: 'Alps',
    'K. Maras': 'Alps',
    'Ankara Province': 'Alps',
    Antalya: 'Alps',
    Ardahan: 'Alps',
    Cankiri: 'Alps',
    Denizli: 'Alps',
    Isparta: 'Alps',
    Karabuk: 'Alps',
    Kastamonu: 'Alps',
    Kocaeli: 'Alps',
    Ordu: 'Alps',
    Samsun: 'Alps',
    Tunceli: 'Alps',
    Van: 'Alps',
  },
  'United Kingdom': {
    Highland: 'Scottish Highlands',
    Aberdeenshire: 'Scottish Highlands',
    Aberdeen: 'Scottish Highlands',
    Moray: 'Scottish Highlands',
    'Dumfries and Galloway': 'Scottish Highlands',
    'South Lanarkshire': 'Scottish Highlands',
    'Westmorland and Furness': 'Appalachians',
    Northumberland: 'Appalachians',
    Durham: 'Appalachians',
  },
  'United States': {
    Colorado: 'Rockies (US)',
    Utah: 'Rockies (US)',
    Wyoming: 'Rockies (US)',
    Montana: 'Rockies (US)',
    Idaho: 'Rockies (US)',
    'New Mexico': 'Rockies (US)',
    Nevada: 'Rockies (US)',
    Arizona: 'Rockies (US)',
    California: 'Sierra Nevada (US)',
    Oregon: 'Sierra Nevada (US)',
    Washington: 'Sierra Nevada (US)',
    Alaska: 'Rockies (US)',
    Vermont: 'Appalachians',
    'New Hampshire': 'Appalachians',
    Maine: 'Appalachians',
    'New York': 'Appalachians',
    Pennsylvania: 'Appalachians',
    Massachusetts: 'Appalachians',
    Connecticut: 'Appalachians',
    'New Jersey': 'Appalachians',
    Maryland: 'Appalachians',
    'West Virginia': 'Appalachians',
    Virginia: 'Appalachians',
    'North Carolina': 'Appalachians',
    Tennessee: 'Appalachians',
    Michigan: 'Appalachians',
    Minnesota: 'Appalachians',
    Wisconsin: 'Appalachians',
    Illinois: 'Appalachians',
    Indiana: 'Appalachians',
    Ohio: 'Appalachians',
    Iowa: 'Appalachians',
    'South Dakota': 'Rockies (US)',
    'North Dakota': 'Appalachians',
    Missouri: 'Appalachians',
    'Rhode Island': 'Appalachians',
    Alabama: 'Appalachians',
  },
  Russia: {
    Krasnodar: 'Carpathians',
    'Kabardino-Balkar': 'Carpathians',
    'Karachay-Cherkess': 'Carpathians',
    'North Ossetia-Alania': 'Carpathians',
    Ingushetia: 'Carpathians',
    Murmansk: 'Scandinavia',
    Karelia: 'Scandinavia',
    Leningrad: 'Scandinavia',
    Komi: 'Scandinavia',
    Arkhangelsk: 'Scandinavia',
    Kamchatka: 'Carpathians',
    Altai: 'Carpathians',
    'Gorno-Altay': 'Carpathians',
    Kemerovo: 'Carpathians',
    Khakassia: 'Carpathians',
    Irkutsk: 'Carpathians',
    Krasnoyarsk: 'Carpathians',
    Buryatia: 'Carpathians',
    Sakhalin: 'Carpathians',
    Primorsky: 'Carpathians',
    Chelyabinsk: 'Carpathians',
    Bashkortostan: 'Carpathians',
    Sverdlovsk: 'Carpathians',
    Perm: 'Carpathians',
    Tomsk: 'Carpathians',
    Novosibirsk: 'Carpathians',
    Orenburg: 'Carpathians',
    Tatarstan: 'Carpathians',
    Udmurt: 'Carpathians',
    'Moscow Oblast': 'Carpathians',
    'Moscow City': 'Carpathians',
    Kaluga: 'Carpathians',
    Tula: 'Carpathians',
    Ryazan: 'Carpathians',
    Vladimir: 'Carpathians',
    Nizhny: 'Carpathians',
    Ivanovo: 'Carpathians',
    Yaroslavl: 'Carpathians',
    Vologda: 'Carpathians',
    Tver: 'Carpathians',
    Pskov: 'Carpathians',
    Voronezh: 'Carpathians',
    Lipetsk: 'Carpathians',
    Tambov: 'Carpathians',
    Mordovia: 'Carpathians',
    Samara: 'Carpathians',
    Saratov: 'Carpathians',
    Oryol: 'Carpathians',
    Khan: 'Carpathians',
  },
  Slovenia: {
    'Upper Carniola': 'Alps',
    Carinthia: 'Alps',
    Savinja: 'Alps',
    'Central Sava': 'Alps',
    'Central Slovenia': 'Alps',
    'Littoral-Inner Carniola': 'Alps',
    Drava: 'Alps',
    Gorizia: 'Alps',
    'Southeast Slovenia': 'Alps',
  },
  Slovakia: {
    Zilina: 'Tatra Mountains',
    Presov: 'Tatra Mountains',
    'Banska Bystrica': 'Tatra Mountains',
    Liptovsky: 'Tatra Mountains',
    Poprad: 'Tatra Mountains',
    Tatry: 'Tatra Mountains',
    Nitriansky: 'Carpathians',
    Bratislava: 'Carpathians',
    Kosice: 'Carpathians',
    Trenciansky: 'Carpathians',
  },
  Ukraine: {
    "Ivano-Frankivs'k": 'Carpathians',
    Zakarpattia: 'Carpathians',
    Lviv: 'Carpathians',
    Chernivtsi: 'Carpathians',
    Ternopil: 'Carpathians',
    Cherkasy: 'Carpathians',
  },
  Georgia: {
    'Mtskheta-Mtianeti': 'Carpathians',
    'Samagrelo-Zemo Svaneti': 'Carpathians',
    'Samtskhe-Javakheti': 'Carpathians',
    Ajaria: 'Carpathians',
  },
  'Bosnia and Herzegovina': {
    'Republic of Srpska': 'Carpathians',
    'Central Bosnia': 'Carpathians',
    Sarajevo: 'Carpathians',
    'West Bosnia': 'Carpathians',
    'Zenica-Doboj': 'Carpathians',
  },
  'New Zealand': {
    'Canterbury Region': 'New Zealand',
    'Otago Region': 'New Zealand',
    'Manawatu-Wanganui Region': 'New Zealand',
    'Marlborough Region': 'New Zealand',
    'Taranaki Region': 'New Zealand',
    'Tasman Region': 'New Zealand',
    'Waikato Region': 'New Zealand',
    'Auckland Region': 'New Zealand',
  },
  Norway: {
    Innlandet: 'Scandinavia',
    Viken: 'Scandinavia',
    'Vestfold og Telemark': 'Scandinavia',
    Agder: 'Scandinavia',
    Vestland: 'Scandinavia',
    'Møre og Romsdal': 'Scandinavia',
    Trøndelag: 'Scandinavia',
    'Troms og Finnmark': 'Scandinavia',
    Nordland: 'Scandinavia',
    Oslo: 'Scandinavia',
    Rogaland: 'Scandinavia',
  },
  Iran: {
    Alborz: 'Carpathians',
    Ardabil: 'Carpathians',
    'Azarbayjan-e Gharbi': 'Carpathians',
    'Azarbayjan-e Sharqi': 'Carpathians',
    'Chahar Mahall va Bakhtiari': 'Carpathians',
    Esfahan: 'Carpathians',
    Fars: 'Carpathians',
    Hamadan: 'Carpathians',
    Khorasan: 'Carpathians',
    'Kohgiluyeh va Buyer Ahmad': 'Carpathians',
    Kordestan: 'Carpathians',
    Markazi: 'Carpathians',
    Tehran: 'Carpathians',
    Zanjan: 'Carpathians',
  },
  India: {
    'Himachal Pradesh': 'Carpathians',
    'Jammu and Kashmir': 'Carpathians',
    Uttarakhand: 'Carpathians',
  },
  Montenegro: {
    Kolasin: 'Carpathians',
    Zabljak: 'Carpathians',
    Andrijevica: 'Carpathians',
    Berane: 'Carpathians',
  },
  Bulgaria: {
    Blagoevgrad: 'Carpathians',
    Kyustendil: 'Carpathians',
    Plovdiv: 'Carpathians',
    Smolyan: 'Carpathians',
    Sofia: 'Carpathians',
    Sofiya: 'Carpathians',
  },
  Croatia: {
    'Grad Zagreb': 'Carpathians',
    Karlovacka: 'Carpathians',
    'Primorsko-goranska': 'Carpathians',
    Zagrebacka: 'Carpathians',
  },
  'North Macedonia': {
    'Bitola Municipality': 'Carpathians',
    'Bogovinje Municipality': 'Carpathians',
    'Kavadarci Municipality': 'Carpathians',
    'Kocani Municipality': 'Carpathians',
    'Krusevo Municipality': 'Carpathians',
    'Mavrovo and Rostusa Municipality': 'Carpathians',
    'Probistip Municipality': 'Carpathians',
    'Tetovo Municipality': 'Carpathians',
  },
  Serbia: {
    'Pirotski upravni okrug': 'Carpathians',
    'Rasinski upravni okrug': 'Carpathians',
    Raska: 'Carpathians',
    Zajecar: 'Carpathians',
    'Zlatiborski upravni okrug': 'Carpathians',
    'Grad Beograd': 'Carpathians',
    Mitrovica: 'Carpathians',
  },
  Kosovo: {
    Ferizaj: 'Carpathians',
    'Jegunovce Municipality': 'Carpathians',
  },
  Hungary: {
    'Borsod-Abauj Zemplen': 'Carpathians',
    Heves: 'Carpathians',
    Budapest: 'Carpathians',
    Pest: 'Carpathians',
    'Komarom-Esztergom': 'Carpathians',
    Veszprem: 'Carpathians',
  },
}

export function mapToRegion(country: string, region: string): Region {
  const countryC = countryOverrides[country] ?? country
  const overrides = regionOverrides[countryC]
  if (overrides) {
    const regionParts = region.split(';')
    for (const part of regionParts) {
      const trimmed = part.trim()
      for (const [key, value] of Object.entries(overrides)) {
        if (trimmed.startsWith(key) || key.startsWith(trimmed)) {
          return value
        }
      }
    }
    const defaultRegion = countryDefault[countryC]
    if (defaultRegion) return defaultRegion
  }

  const defaultRegion = countryDefault[countryC]
  if (defaultRegion) return defaultRegion

  return 'Alps'
}

const countryOverrides: Record<string, string> = {
  'Czech Republic': 'Czechia',
}

export function validateRegionMappings(): string[] {
  const validRegions = new Set(REGIONS)
  const errors: string[] = []
  for (const [country, defaultRegion] of Object.entries(countryDefault)) {
    if (!validRegions.has(defaultRegion)) {
      errors.push(
        `countryDefault[${country}] = "${defaultRegion}" is not a valid Region`
      )
    }
  }
  for (const [country, overrides] of Object.entries(regionOverrides)) {
    for (const [region, mappedRegion] of Object.entries(overrides)) {
      if (!validRegions.has(mappedRegion)) {
        errors.push(
          `regionOverrides[${country}][${region}] = "${mappedRegion}" is not a valid Region`
        )
      }
    }
  }
  return errors
}
