/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2463488399',
          max: 0,
          min: 0,
          name: 'input_hash',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'select2363381545',
          maxSelect: 1,
          name: 'type',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['analysis', 'preference-search'],
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_3247561751',
          help: '',
          hidden: false,
          id: 'relation3219494002',
          maxSelect: 1,
          minSelect: 0,
          name: 'proposal',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_1630916145',
          help: '',
          hidden: false,
          id: 'relation1985410363',
          maxSelect: 1,
          minSelect: 0,
          name: 'trip',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'select2063623452',
          maxSelect: 1,
          name: 'status',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['generating', 'complete', 'error'],
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2131879744',
          max: 0,
          min: 0,
          name: 'thinking',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text4274335913',
          max: 0,
          min: 0,
          name: 'content',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text3616895705',
          max: 0,
          min: 0,
          name: 'model',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
      ],
      id: 'pbc_804077199',
      indexes: [],
      listRule: null,
      name: 'llm_cache',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_804077199')

    return app.delete(collection)
  }
)
