/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3142635823',
          help: '',
          hidden: false,
          id: 'relation562457621',
          maxSelect: 1,
          minSelect: 0,
          name: 'proposer',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text3016830085',
          max: 0,
          min: 0,
          name: 'proposer_name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_1630916145',
          help: '',
          hidden: false,
          id: 'relation1985410363',
          maxSelect: 1,
          minSelect: 0,
          name: 'trip',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'select2744374011',
          maxSelect: 1,
          name: 'state',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['draft', 'submitted', 'rejected'],
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text1843675174',
          max: 0,
          min: 0,
          name: 'description',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text344108856',
          max: 0,
          min: 0,
          name: 'resort_name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'date2502384312',
          max: '',
          min: '',
          name: 'start_date',
          presentable: false,
          required: true,
          system: false,
          type: 'date',
        },
        {
          help: '',
          hidden: false,
          id: 'date2220669758',
          max: '',
          min: '',
          name: 'end_date',
          presentable: false,
          required: true,
          system: false,
          type: 'date',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2512256107',
          max: 0,
          min: 0,
          name: 'nearest_airport',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'number1466020903',
          max: null,
          min: null,
          name: 'transfer_time',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text1400097126',
          max: 0,
          min: 0,
          name: 'country',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text258142582',
          max: 0,
          min: 0,
          name: 'region',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'number4129603711',
          max: null,
          min: null,
          name: 'summit_altitude',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number4045473482',
          max: null,
          min: null,
          name: 'base_altitude',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number2292891546',
          max: null,
          min: null,
          name: 'piste_km',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number1176532198',
          max: null,
          min: null,
          name: 'beginner_pct',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number3749751439',
          max: null,
          min: null,
          name: 'intermediate_pct',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number234042106',
          max: null,
          min: null,
          name: 'advanced_pct',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number1746005806',
          max: null,
          min: null,
          name: 'lift_count',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'select2863221042',
          maxSelect: 1,
          name: 'snow_reliability',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['high', 'medium', 'low'],
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text862227337',
          max: 0,
          min: 0,
          name: 'ski_season_months',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'json623368077',
          maxSize: 0,
          name: 'websites',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text1092145443',
          max: 0,
          min: 0,
          name: 'latitude',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2246143851',
          max: 0,
          min: 0,
          name: 'longitude',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2664976940',
          max: 0,
          min: 0,
          name: 'linked_resorts_description',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
      ],
      id: 'pbc_3247561751',
      indexes: [],
      listRule: "@request.auth.id != ''",
      name: 'proposals',
      system: false,
      type: 'base',
      updateRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_3247561751')

    return app.delete(collection)
  }
)
