[[pre-start]]
deps = "bun install"

[[pre-start]]
copy = "wt step copy-from-main --yes"

[aliases]

# Intended to be used within a worktree to sync work back to main.
merge-and-continue = "wt merge --no-commit --no-squash --no-remove && wt step copy-to-main --yes"

# Can be used from any worktree.
sync-all-from-main = "wt step for-each -- sh -c 'git rebase main && wt step copy-from-main --yes'"

# Use from within a worktree to copy e.g. .env files to/from main.
copy-to-main = "wt step copy-ignored --from {{ branch }} --to {{ default_branch }} --force"
copy-from-main = "wt step copy-ignored --from {{ default_branch }} --to {{ branch }} --force"
