export const COUNTRY_CODES: Record<string, string> = {
  Andorra: 'AD',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Belarus: 'BY',
  'Bosnia and Herzegovina': 'BA',
  Bulgaria: 'BG',
  Canada: 'CA',
  Chile: 'CL',
  China: 'CN',
  Croatia: 'HR',
  Cyprus: 'CY',
  Czechia: 'CZ',
  Estonia: 'EE',
  Finland: 'FI',
  France: 'FR',
  Georgia: 'GE',
  Germany: 'DE',
  Greece: 'GR',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Iran: 'IR',
  Israel: 'IL',
  Italy: 'IT',
  Japan: 'JP',
  Kazakhstan: 'KZ',
  Kosovo: 'XK',
  Kyrgyzstan: 'KG',
  Latvia: 'LV',
  Lebanon: 'LB',
  Liechtenstein: 'LI',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  'North Korea': 'KP',
  'North Macedonia': 'MK',
  Norway: 'NO',
  Poland: 'PL',
  Portugal: 'PT',
  Romania: 'RO',
  Russia: 'RU',
  Serbia: 'RS',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Korea': 'KR',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Turkey: 'TR',
  Ukraine: 'UA',
  'United Kingdom': 'GB',
  'United States': 'US',
  Uzbekistan: 'UZ',
}

export const COUNTRIES = Object.keys(COUNTRY_CODES)
  .filter((name) => !name.includes('_'))
  .sort()

export function getCountryFlagUrl(country: string): string | undefined {
  const code = COUNTRY_CODES[country]
  if (!code) return undefined
  return `/flags/${code.toLowerCase()}.png`
}
