export const colors = {
  accent: 'var(--color-accent)',
  bgPrimary: 'var(--color-bgPrimary)',
  bgCard: 'var(--color-bgCard)',
  bgInput: 'var(--color-bgInput)',
  textPrimary: 'var(--color-textPrimary)',
  textSecondary: 'var(--color-textSecondary)',
  textData: 'var(--color-textData)',
  error: 'var(--color-error)',
  pisteBeginner: 'var(--color-pisteBeginner)',
  pisteIntermediate: 'var(--color-pisteIntermediate)',
  pisteAdvanced: 'var(--color-pisteAdvanced)',
  timeEating: 'var(--color-timeEating)',
  timeApres: 'var(--color-timeApres)',
  timeHotel: 'var(--color-timeHotel)',
  snowboard: 'var(--color-snowboard)',
  slopeBlack: 'var(--color-slopeBlack)',
  slopeRed: 'var(--color-slopeRed)',
  slopeBlue: 'var(--color-slopeBlue)',
  onPiste: 'var(--color-onPiste)',
  offPiste: 'var(--color-offPiste)',
  hotel5Star: 'var(--color-hotel5Star)',
  hotel: 'var(--color-hotel)',
  chalet: 'var(--color-chalet)',
  guesthouse: 'var(--color-guesthouse)',
  palette0: 'var(--color-palette0)',
  palette1: 'var(--color-palette1)',
  palette2: 'var(--color-palette2)',
  palette3: 'var(--color-palette3)',
  palette4: 'var(--color-palette4)',
  palette5: 'var(--color-palette5)',
  palette6: 'var(--color-palette6)',
  palette7: 'var(--color-palette7)',
  medalGold: 'var(--color-medalGold)',
  medalSilver: 'var(--color-medalSilver)',
  medalBronze: 'var(--color-medalBronze)',
}

export function mix(token: string, opacity: number): string {
  return `color-mix(in srgb, var(${token}) ${opacity * 100}%, transparent)`
}

export const fontSizes = {
  xs: '12px',
  sm: '13px',
  base: '14px',
  md: '16px',
  lg: '20px',
  xl: '24px',
  '2xl': 'clamp(24px, 4vw, 30px)',
  '3xl': 'clamp(28px, 5vw, 40px)',
} as const

export const fonts = {
  body: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
  display: "Palatino, 'Palatino Linotype', 'Book Antiqua', Georgia, serif",
  mono: 'monospace',
}

export const borders = {
  subtle: `1px solid ${mix('--color-textSecondary', 0.3)}`,
  card: `1px solid ${mix('--color-accent', 0.14)}`,
  muted: `1px solid ${mix('--color-accent', 0.18)}`,
  accent: `1px solid ${mix('--color-accent', 0.3)}`,
}

export const formStyles = {
  error: {
    color: colors.error,
    fontFamily: fonts.body,
    fontSize: fontSizes.sm,
    margin: 0,
  },
  primaryButton: {
    marginTop: '4px',
    padding: '14px',
    borderRadius: '8px',
    border: 'none',
    background: colors.accent,
    color: colors.bgPrimary,
    fontFamily: fonts.body,
    fontSize: fontSizes.md,
  },
  cancelButton: {
    padding: '10px 16px',
    borderRadius: '7px',
    border: 'none',
    background: 'transparent',
    color: colors.textSecondary,
    fontFamily: fonts.body,
    fontSize: fontSizes.base,
    cursor: 'pointer',
  },
  saveButton: {
    padding: '10px 24px',
    borderRadius: '7px',
    border: 'none',
    background: colors.accent,
    color: colors.bgPrimary,
    fontFamily: fonts.body,
    fontSize: fontSizes.base,
    fontWeight: '600',
    cursor: 'pointer',
  },
}

export const authStyles = {
  container: {
    minHeight: '100dvh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background:
      'linear-gradient(160deg, var(--color-bgPrimary) 0%, var(--color-bgCard) 50%, var(--color-bgPrimary) 100%)',
    padding: '24px',
  },
  card: {
    position: 'relative' as const,
    zIndex: 1,
    background: colors.bgCard,
    borderRadius: '16px',
    padding: '48px 44px',
    width: '100%',
    maxWidth: '420px',
    border: borders.card,
    boxShadow: `0 24px 80px var(--color-shadow), 0 0 0 1px ${mix('--color-accent', 0.04)}`,
  },
  brandName: {
    fontFamily: fonts.body,
    fontSize: fontSizes.xs,
    fontWeight: '500',
    letterSpacing: '0.45em',
    color: colors.accent,
    textTransform: 'uppercase' as const,
  },
  title: {
    fontFamily: fonts.display,
    marginBottom: '32px',
    fontSize: fontSizes['3xl'],
    fontWeight: '600',
    color: colors.textPrimary,
    lineHeight: '1.1',
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  switchText: {
    marginTop: '28px',
    fontFamily: fonts.body,
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
    textAlign: 'center' as const,
  },
  switchLink: {
    background: 'none',
    border: 'none',
    color: colors.accent,
    fontFamily: fonts.body,
    fontWeight: '500',
    cursor: 'pointer',
    fontSize: fontSizes.sm,
    padding: '0',
  },
}

export const mdStyles = {
  h1: {
    fontFamily: fonts.display,
    fontSize: fontSizes['2xl'],
    fontWeight: '600' as const,
    color: colors.textPrimary,
    margin: '0 0 16px',
    lineHeight: 1.2,
  },
  h2: {
    fontFamily: fonts.display,
    fontSize: fontSizes.xl,
    fontWeight: '600' as const,
    color: colors.textPrimary,
    margin: '24px 0 12px',
    lineHeight: 1.3,
  },
  h3: {
    fontFamily: fonts.display,
    fontSize: fontSizes.lg,
    fontWeight: '600' as const,
    color: colors.textPrimary,
    margin: '20px 0 8px',
    lineHeight: 1.4,
  },
  p: {
    margin: '0 0 12px',
  },
  ul: {
    margin: '0 0 12px',
    paddingLeft: '24px',
    listStyleType: 'disc' as const,
  },
  ol: {
    margin: '0 0 12px',
    paddingLeft: '24px',
    listStyleType: 'decimal' as const,
  },
  li: {
    marginBottom: '4px',
  },
  a: {
    color: colors.accent,
    textDecoration: 'underline' as const,
  },
  blockquote: {
    margin: '0 0 12px',
    paddingLeft: '16px',
    borderLeft: `3px solid ${colors.accent}`,
    color: colors.textSecondary,
    fontStyle: 'italic' as const,
  },
  inlineCode: {
    fontFamily: fonts.mono,
    fontSize: fontSizes.sm,
    padding: '2px 4px',
    borderRadius: '3px',
  },
  codeBlock: {
    fontFamily: fonts.mono,
    fontSize: fontSizes.sm,
  },
  pre: {
    fontFamily: fonts.mono,
    fontSize: fontSizes.sm,
    background: colors.bgInput,
    padding: '16px',
    borderRadius: '8px',
    overflowX: 'auto' as const,
    margin: '0 0 12px',
  },
  table: {
    borderCollapse: 'collapse' as const,
    width: '100%',
    margin: '0 0 12px',
    fontSize: fontSizes.sm,
  },
  th: {
    border: `1px solid ${mix('--color-textSecondary', 0.3)}`,
    padding: '8px 12px',
    textAlign: 'left' as const,
    fontWeight: '600' as const,
  },
  td: {
    border: `1px solid ${mix('--color-textSecondary', 0.3)}`,
    padding: '8px 12px',
  },
  hr: {
    border: 'none',
    borderTop: `1px solid ${mix('--color-textSecondary', 0.3)}`,
    margin: '16px 0',
  },
} as const

export const detailStyles = {
  title: {
    fontFamily: fonts.display,
    fontSize: fontSizes.xl,
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
    display: 'inline-flex' as const,
    alignItems: 'center',
    gap: '6px',
  },
  websiteLink: {
    fontFamily: fonts.body,
    fontSize: fontSizes.sm,
    color: colors.accent,
    wordBreak: 'break-all' as const,
  },
  descriptionText: {
    fontFamily: fonts.body,
    fontSize: fontSizes.base,
    color: colors.textData,
    lineHeight: '1.6',
    margin: '4px 0 0',
  },
} as const

export const overlayStyles = {
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'var(--color-overlay)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 300,
  },
  panel: {
    background: colors.bgCard,
    border: borders.card,
    borderRadius: '12px',
    width: '100%',
    maxWidth: '560px',
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column' as const,
    boxShadow: '0 24px 80px var(--color-shadow)',
    margin: '16px',
    overflow: 'hidden',
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px 28px',
    position: 'sticky' as const,
    top: 0,
    background: colors.bgCard,
    borderBottom: borders.subtle,
    zIndex: 1,
    flexShrink: 0,
  },
  panelTitle: {
    fontFamily: fonts.display,
    fontSize: fontSizes['2xl'],
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
  },
  closeButton: {
    background: 'none',
    border: 'none',
    color: colors.textSecondary,
    cursor: 'pointer',
    padding: '4px 8px',
    lineHeight: 1,
    borderRadius: '4px',
  },
  panelContent: {
    flex: 1,
    overflowY: 'auto' as const,
    overflowX: 'hidden' as const,
    padding: '20px 28px 28px',
  },
  panelFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '12px',
    padding: '16px 28px',
    position: 'sticky' as const,
    bottom: 0,
    background: colors.bgCard,
    borderTop: borders.subtle,
    zIndex: 1,
    flexShrink: 0,
  },
} as const

export const srOnly = {
  position: 'absolute' as const,
  width: '1px',
  height: '1px',
  padding: 0,
  margin: '-1px' as const,
  overflow: 'hidden' as const,
  clip: 'rect(0, 0, 0, 0)' as const,
  whiteSpace: 'nowrap' as const,
  borderWidth: 0,
} as const

export const fieldStyles = {
  default: {
    field: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '7px',
    },
    label: {
      fontFamily: fonts.body,
      fontSize: fontSizes.xs,
      fontWeight: '500',
      color: colors.textSecondary,
      letterSpacing: '0.08em',
      textTransform: 'uppercase' as const,
    },
    input: {
      height: '40px',
      padding: '10px 14px',
      borderRadius: '7px',
      border: borders.card,
      background: colors.bgInput,
      color: colors.textPrimary,
      fontFamily: fonts.body,
      fontSize: fontSizes.base,
      outline: 'none' as const,
    },
  },
  auth: {
    field: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '8px',
      textAlign: 'left' as const,
    },
    label: {
      fontFamily: fonts.body,
      fontSize: fontSizes.xs,
      fontWeight: '500',
      color: colors.textSecondary,
      letterSpacing: '0.08em',
      textTransform: 'uppercase' as const,
    },
    input: {
      padding: '12px 16px',
      borderRadius: '8px',
      border: borders.card,
      background: colors.bgInput,
      color: colors.textPrimary,
      fontFamily: fonts.body,
      fontSize: fontSizes.md,
      outline: 'none' as const,
    },
  },
}
