/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const snapshot = [
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1582905952',
            max: 0,
            min: 0,
            name: 'method',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2279338944',
        indexes: [
          'CREATE INDEX `idx_mfas_collectionRef_recordRef` ON `_mfas` (collectionRef,recordRef)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_mfas',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 8,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 0,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: true,
            id: 'text3866985172',
            max: 0,
            min: 0,
            name: 'sentTo',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_1638494021',
        indexes: [
          'CREATE INDEX `idx_otps_collectionRef_recordRef` ON `_otps` (collectionRef, recordRef)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_otps',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2462348188',
            max: 0,
            min: 0,
            name: 'provider',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1044722854',
            max: 0,
            min: 0,
            name: 'providerId',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2281828961',
        indexes: [
          'CREATE UNIQUE INDEX `idx_externalAuths_record_provider` ON `_externalAuths` (collectionRef, recordRef, provider)',
          'CREATE UNIQUE INDEX `idx_externalAuths_collection_provider` ON `_externalAuths` (collectionRef, provider, providerId)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_externalAuths',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text4228609354',
            max: 0,
            min: 0,
            name: 'fingerprint',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_4275539003',
        indexes: [
          'CREATE UNIQUE INDEX `idx_authOrigins_unique_pairs` ON `_authOrigins` (collectionRef, recordRef, fingerprint)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_authOrigins',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 86400,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: null,
        deleteRule: null,
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            help: '',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: 'pbc_3142635823',
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey_pbc_3142635823` ON `_superusers` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email_pbc_3142635823` ON `_superusers` (`email`) WHERE `email` != ''",
        ],
        listRule: null,
        manageRule: null,
        mfa: {
          duration: 600,
          enabled: false,
          rule: '',
        },
        name: '_superusers',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: '',
            id: '',
            name: '',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: true,
        type: 'auth',
        updateRule: null,
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p><i>If you didn\'t recently register, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 86400,
        },
        viewRule: null,
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 432000,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: '',
        deleteRule: 'id = @request.auth.id',
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            help: '',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1579384326',
            max: 255,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'file376926767',
            maxSelect: 1,
            maxSize: 0,
            mimeTypes: [
              'image/jpeg',
              'image/png',
              'image/svg+xml',
              'image/gif',
              'image/webp',
            ],
            name: 'avatar',
            presentable: false,
            protected: false,
            required: false,
            system: false,
            thumbs: null,
            type: 'file',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: '_pb_users_auth_',
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != ''",
        ],
        listRule: 'id = @request.auth.id',
        manageRule: null,
        mfa: {
          duration: 600,
          enabled: false,
          rule: '',
        },
        name: 'users',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: 'avatar',
            id: '',
            name: 'name',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: true,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: false,
        type: 'auth',
        updateRule: 'id = @request.auth.id',
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p><i>If you didn\'t recently register, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 86400,
        },
        viewRule: 'id = @request.auth.id',
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1997877400',
            max: 0,
            min: 0,
            name: 'code',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1843675174',
            max: 200000,
            min: 0,
            name: 'description',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_1630916145',
        indexes: ['CREATE UNIQUE INDEX `idx_trips_code` ON `trips` (`code`)'],
        listRule: "@request.auth.id != ''",
        name: 'trips',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: false,
            collectionId: '_pb_users_auth_',
            help: '',
            hidden: false,
            id: 'relation2375276105',
            maxSelect: 1,
            minSelect: 0,
            name: 'user',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1579384326',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_1630916145',
            help: '',
            hidden: false,
            id: 'relation1985410363',
            maxSelect: 1,
            minSelect: 0,
            name: 'trip',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'select1466534506',
            maxSelect: 1,
            name: 'role',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['coordinator', 'participant'],
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_653341844',
        indexes: [],
        listRule: "@request.auth.id != ''",
        name: 'participants',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: false,
            collectionId: '_pb_users_auth_',
            help: '',
            hidden: false,
            id: 'relation562457621',
            maxSelect: 1,
            minSelect: 0,
            name: 'proposer',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3016830085',
            max: 0,
            min: 0,
            name: 'proposer_name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_1630916145',
            help: '',
            hidden: false,
            id: 'relation1985410363',
            maxSelect: 1,
            minSelect: 0,
            name: 'trip',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'select2744374011',
            maxSelect: 1,
            name: 'state',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['draft', 'submitted', 'rejected'],
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1843675174',
            max: 200000,
            min: 0,
            name: 'description',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text344108856',
            max: 0,
            min: 0,
            name: 'resort_name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'date2502384312',
            max: '',
            min: '',
            name: 'start_date',
            presentable: false,
            required: true,
            system: false,
            type: 'date',
          },
          {
            help: '',
            hidden: false,
            id: 'date2220669758',
            max: '',
            min: '',
            name: 'end_date',
            presentable: false,
            required: true,
            system: false,
            type: 'date',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2512256107',
            max: 0,
            min: 0,
            name: 'nearest_airport',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'number1466020903',
            max: null,
            min: null,
            name: 'transfer_time',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1400097126',
            max: 0,
            min: 0,
            name: 'country',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text258142582',
            max: 0,
            min: 0,
            name: 'region',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'number4129603711',
            max: null,
            min: null,
            name: 'summit_altitude',
            onlyInt: false,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number4045473482',
            max: null,
            min: null,
            name: 'base_altitude',
            onlyInt: false,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number2292891546',
            max: null,
            min: null,
            name: 'piste_km',
            onlyInt: false,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number1176532198',
            max: null,
            min: null,
            name: 'beginner_pct',
            onlyInt: false,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number3749751439',
            max: null,
            min: null,
            name: 'intermediate_pct',
            onlyInt: false,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number234042106',
            max: null,
            min: null,
            name: 'advanced_pct',
            onlyInt: false,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number1746005806',
            max: null,
            min: null,
            name: 'lift_count',
            onlyInt: false,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'select2863221042',
            maxSelect: 1,
            name: 'snow_reliability',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['high', 'medium', 'low'],
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2664976940',
            max: 200000,
            min: 0,
            name: 'linked_resorts_description',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text862227337',
            max: 0,
            min: 0,
            name: 'ski_season_months',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'json623368077',
            maxSize: 0,
            name: 'websites',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1092145443',
            max: 0,
            min: 0,
            name: 'latitude',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2246143851',
            max: 0,
            min: 0,
            name: 'longitude',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_3247561751',
        indexes: [],
        listRule: "@request.auth.id != ''",
        name: 'proposals',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3247561751',
            help: '',
            hidden: false,
            id: 'relation3219494002',
            maxSelect: 1,
            minSelect: 0,
            name: 'proposal',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1579384326',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'url4101391790',
            name: 'url',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text405181692',
            max: 0,
            min: 0,
            name: 'cost',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1843675174',
            max: 200000,
            min: 0,
            name: 'description',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_3480351616',
        indexes: [],
        listRule: "@request.auth.id != ''",
        name: 'accommodations',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: false,
            collectionId: '_pb_users_auth_',
            help: '',
            hidden: false,
            id: 'relation3154569827',
            maxSelect: 1,
            minSelect: 0,
            name: 'creator',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text682311642',
            max: 0,
            min: 0,
            name: 'creator_name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_1630916145',
            help: '',
            hidden: false,
            id: 'relation1985410363',
            maxSelect: 1,
            minSelect: 0,
            name: 'trip',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'select2744374011',
            maxSelect: 1,
            name: 'state',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['open', 'closed'],
          },
          {
            help: '',
            hidden: false,
            id: 'json2118807533',
            maxSize: 0,
            name: 'proposal_ids',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            help: '',
            hidden: false,
            id: 'date2502384312',
            max: '',
            min: '',
            name: 'start_date',
            presentable: false,
            required: true,
            system: false,
            type: 'date',
          },
          {
            help: '',
            hidden: false,
            id: 'date2220669758',
            max: '',
            min: '',
            name: 'end_date',
            presentable: false,
            required: true,
            system: false,
            type: 'date',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text817655234',
            max: 0,
            min: 0,
            name: 'outcome',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_3598350341',
        indexes: [],
        listRule: "@request.auth.id != ''",
        name: 'polls',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3598350341',
            help: '',
            hidden: false,
            id: 'relation2226977349',
            maxSelect: 1,
            minSelect: 0,
            name: 'poll',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            cascadeDelete: false,
            collectionId: '_pb_users_auth_',
            help: '',
            hidden: false,
            id: 'relation646728281',
            maxSelect: 1,
            minSelect: 0,
            name: 'voter',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3915217470',
            max: 0,
            min: 0,
            name: 'voter_name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'json2118807533',
            maxSize: 0,
            name: 'proposal_ids',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            help: '',
            hidden: false,
            id: 'json3109009721',
            maxSize: 0,
            name: 'token_counts',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_2597176356',
        indexes: [],
        listRule: "@request.auth.id != ''",
        name: 'votes',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: false,
            collectionId: '_pb_users_auth_',
            help: '',
            hidden: false,
            id: 'relation2375276105',
            maxSelect: 1,
            minSelect: 0,
            name: 'user',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'select3421403904',
            maxSelect: 2,
            name: 'ski_snowboard',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['Ski', 'Snowboard'],
          },
          {
            help: '',
            hidden: false,
            id: 'select3144380399',
            maxSelect: 3,
            name: 'difficulty',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['Black', 'Red', 'Blue'],
          },
          {
            help: '',
            hidden: false,
            id: 'select1508003959',
            maxSelect: 2,
            name: 'piste',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['On-Piste', 'Off-Piste'],
          },
          {
            help: '',
            hidden: false,
            id: 'number3748805399',
            max: null,
            min: null,
            name: 'time_slopes',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number2678873079',
            max: null,
            min: null,
            name: 'time_eating',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number3402558298',
            max: null,
            min: null,
            name: 'time_apres',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'number1176616869',
            max: null,
            min: null,
            name: 'time_hotel',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'select758666258',
            maxSelect: 4,
            name: 'accommodation',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: [
              '5-star hotel with spa etc',
              '4-star or below hotel',
              'Chalet',
              'Pension/guesthouse',
            ],
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text18589324',
            max: 200000,
            min: 0,
            name: 'notes',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_432047489',
        indexes: [
          'CREATE UNIQUE INDEX `idx_preferences_user` ON `preferences` (`user`)',
        ],
        listRule: "@request.auth.id != ''",
        name: 'preferences',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3247561751',
            help: '',
            hidden: false,
            id: 'relation3219494002',
            maxSelect: 1,
            minSelect: 0,
            name: 'proposal',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            cascadeDelete: false,
            collectionId: '_pb_users_auth_',
            help: '',
            hidden: false,
            id: 'relation3182418120',
            maxSelect: 1,
            minSelect: 0,
            name: 'author',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3133994713',
            max: 0,
            min: 0,
            name: 'author_name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3685223346',
            max: 200000,
            min: 0,
            name: 'body',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'select2363381545',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['comment', 'system'],
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_1040828831',
        indexes: [],
        listRule: "@request.auth.id != ''",
        name: 'discussion',
        system: false,
        type: 'base',
        updateRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2463488399',
            max: 0,
            min: 0,
            name: 'input_hash',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'select2363381545',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['analysis', 'preference-search'],
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3247561751',
            help: '',
            hidden: false,
            id: 'relation3219494002',
            maxSelect: 1,
            minSelect: 0,
            name: 'proposal',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_1630916145',
            help: '',
            hidden: false,
            id: 'relation1985410363',
            maxSelect: 1,
            minSelect: 0,
            name: 'trip',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'select2063623452',
            maxSelect: 1,
            name: 'status',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['generating', 'complete', 'error'],
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2131879744',
            max: 200000,
            min: 0,
            name: 'thinking',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text4274335913',
            max: 200000,
            min: 0,
            name: 'content',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3616895705',
            max: 0,
            min: 0,
            name: 'model',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_804077199',
        indexes: [
          'CREATE INDEX `idx_llm_cache_input_hash` ON `llm_cache` (`input_hash`)',
        ],
        listRule: null,
        name: 'llm_cache',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'file2359244304',
            maxSelect: 1,
            maxSize: 33554432,
            mimeTypes: null,
            name: 'file',
            presentable: false,
            protected: false,
            required: true,
            system: false,
            thumbs: null,
            type: 'file',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_669819519',
        indexes: [],
        listRule: "@request.auth.id != ''",
        name: 'resorts',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: "@request.auth.id != ''",
      },
    ]

    return app.importCollections(snapshot, false)
  },
  (app) => {
    return null
  }
)
