/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3142635823',
          help: '',
          hidden: false,
          id: 'relation2375276105',
          maxSelect: 1,
          minSelect: 0,
          name: 'user',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'select3421403904',
          maxSelect: 2,
          name: 'ski_snowboard',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['Ski', 'Snowboard'],
        },
        {
          help: '',
          hidden: false,
          id: 'select3144380399',
          maxSelect: 3,
          name: 'difficulty',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['Black', 'Red', 'Blue'],
        },
        {
          help: '',
          hidden: false,
          id: 'select1508003959',
          maxSelect: 2,
          name: 'piste',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['On-Piste', 'Off-Piste'],
        },
        {
          help: '',
          hidden: false,
          id: 'number3748805399',
          max: null,
          min: null,
          name: 'time_slopes',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number2678873079',
          max: null,
          min: null,
          name: 'time_eating',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number3402558298',
          max: null,
          min: null,
          name: 'time_apres',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'number1176616869',
          max: null,
          min: null,
          name: 'time_hotel',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          help: '',
          hidden: false,
          id: 'select758666258',
          maxSelect: 4,
          name: 'accommodation',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: [
            '5-star hotel with spa etc',
            '4-star or below hotel',
            'Chalet',
            'Pension/guesthouse',
          ],
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text18589324',
          max: 0,
          min: 0,
          name: 'notes',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
      ],
      id: 'pbc_432047489',
      indexes: [],
      listRule: "@request.auth.id != ''",
      name: 'preferences',
      system: false,
      type: 'base',
      updateRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_432047489')

    return app.delete(collection)
  }
)
