/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3142635823',
          help: '',
          hidden: false,
          id: 'relation3154569827',
          maxSelect: 1,
          minSelect: 0,
          name: 'creator',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text682311642',
          max: 0,
          min: 0,
          name: 'creator_name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_1630916145',
          help: '',
          hidden: false,
          id: 'relation1985410363',
          maxSelect: 1,
          minSelect: 0,
          name: 'trip',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'select2744374011',
          maxSelect: 1,
          name: 'state',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['open', 'closed'],
        },
        {
          help: '',
          hidden: false,
          id: 'json2118807533',
          maxSize: 0,
          name: 'proposal_ids',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          help: '',
          hidden: false,
          id: 'date2502384312',
          max: '',
          min: '',
          name: 'start_date',
          presentable: false,
          required: true,
          system: false,
          type: 'date',
        },
        {
          help: '',
          hidden: false,
          id: 'date2220669758',
          max: '',
          min: '',
          name: 'end_date',
          presentable: false,
          required: true,
          system: false,
          type: 'date',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text817655234',
          max: 0,
          min: 0,
          name: 'outcome',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
      ],
      id: 'pbc_3598350341',
      indexes: [],
      listRule: "@request.auth.id != ''",
      name: 'polls',
      system: false,
      type: 'base',
      updateRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_3598350341')

    return app.delete(collection)
  }
)
