/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_3598350341',
          help: '',
          hidden: false,
          id: 'relation2226977349',
          maxSelect: 1,
          minSelect: 0,
          name: 'poll',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3142635823',
          help: '',
          hidden: false,
          id: 'relation646728281',
          maxSelect: 1,
          minSelect: 0,
          name: 'voter',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text3915217470',
          max: 0,
          min: 0,
          name: 'voter_name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'json2118807533',
          maxSize: 0,
          name: 'proposal_ids',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          help: '',
          hidden: false,
          id: 'json3109009721',
          maxSize: 0,
          name: 'token_counts',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
      ],
      id: 'pbc_2597176356',
      indexes: [],
      listRule: "@request.auth.id != ''",
      name: 'votes',
      system: false,
      type: 'base',
      updateRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_2597176356')

    return app.delete(collection)
  }
)
