/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_3247561751',
          help: '',
          hidden: false,
          id: 'relation3219494002',
          maxSelect: 1,
          minSelect: 0,
          name: 'proposal',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text1579384326',
          max: 0,
          min: 0,
          name: 'name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url4101391790',
          name: 'url',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text405181692',
          max: 0,
          min: 0,
          name: 'cost',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text1843675174',
          max: 0,
          min: 0,
          name: 'description',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
      ],
      id: 'pbc_3480351616',
      indexes: [],
      listRule: "@request.auth.id != ''",
      name: 'accommodations',
      system: false,
      type: 'base',
      updateRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_3480351616')

    return app.delete(collection)
  }
)
