name: Bun CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: test-app
    runs-on: ubuntu-latest
    env:
      PUBLIC_APPWRITE_ENDPOINT: https://fra.cloud.appwrite.io/v1
      PUBLIC_APPWRITE_PROJECT_ID: 69b05f0a00097b02b873
      PUBLIC_APPWRITE_DATABASE_ID: 69b80ecc00135af5ff33
      PUBLIC_APPWRITE_TRIPS_COLLECTION_ID: trips
      PUBLIC_APPWRITE_PARTICIPANTS_COLLECTION_ID: participants
      PUBLIC_APPWRITE_PROPOSALS_COLLECTION_ID: proposals
      PUBLIC_APPWRITE_POLLS_COLLECTION_ID: polls
      PUBLIC_APPWRITE_VOTES_COLLECTION_ID: votes
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun run test
